
jobs:
  test:
    docker:
      - image: python:3.9.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: linting
          command: |
            pip install flake8
            flake8
      - run:
          name: tests
          command: |
            python setup.py install
            
            pip install pytest pytest-cov codecov
            echo "backend: Agg" > "matplotlibrc"

            pytest --cov=evaltools --junitxml=tests/test-reports/report.xml tests
          environment:
            PYTHONHASHSEED: "0"
      - store_test_results:
          path: tests/test-reports
      - store_artifacts:
          path: tests/test-reports

  deploy:
    docker:
      - image: python:3.9.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install --upgrade setuptools wheel twine
      - run:
          name: set up .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create package
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
      - run:
          name: upload to pypi
          command: |
            twine upload dist/*

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
